pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.PREFER_SETTINGS
    repositories {
        mavenLocal()
        google()
        mavenCentral()
    }
}

rootProject.name = "farebot"

include(":base")
include(":card")
include(":card:cepas")
include(":card:china")
include(":card:classic")
include(":card:desfire")
include(":card:felica")
include(":card:iso7816")
include(":card:ksx6924")
include(":card:ultralight")
include(":card:vicinity")
include(":transit")
include(":transit:adelaide")
include(":transit:amiibo")
include(":transit:bilhete")
include(":transit:bip")
include(":transit:bonobus")
include(":transit:calypso")
include(":transit:charlie")
include(":transit:chc-metrocard")
include(":transit:china")
include(":transit:cifial")
include(":transit:clipper")
include(":transit:easycard")
include(":transit:edy")
include(":transit:en1545")
include(":transit:erg")
include(":transit:ezlink")
include(":transit:gautrain")
include(":transit:hafilat")
include(":transit:hsl")
include(":transit:intercard")
include(":transit:kazan")
include(":transit:kiev")
include(":transit:kmt")
include(":transit:komuterlink")
include(":transit:krocap")
include(":transit:lax-tap")
include(":transit:magnacarta")
include(":transit:manly")
include(":transit:metromoney")
include(":transit:metroq")
include(":transit:mrtj")
include(":transit:msp-goto")
include(":transit:myki")
include(":transit:ndef")
include(":transit:nextfare")
include(":transit:nextfareul")
include(":transit:octopus")
include(":transit:opal")
include(":transit:orca")
include(":transit:otago")
include(":transit:ovc")
include(":transit:oyster")
include(":transit:pilet")
include(":transit:podorozhnik")
include(":transit:ricaricami")
include(":transit:rkf")
include(":transit:selecta")
include(":transit:seqgo")
include(":transit:serialonly")
include(":transit:smartrider")
include(":transit:snapper")
include(":transit:suica")
include(":transit:tampere")
include(":transit:tfi-leap")
include(":transit:tmoney")
include(":transit:touchngo")
include(":transit:troika")
include(":transit:umarsh")
include(":transit:ventra")
include(":transit:vicinity")
include(":transit:waikato")
include(":transit:warsaw")
include(":transit:yargor")
include(":transit:yvr-compass")
include(":transit:zolotayakorona")
include(":app")
include(":app:android")
include(":app:desktop")
include(":tools:mdst")
