pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.PREFER_SETTINGS
    repositories {
        mavenLocal()
        google()
        mavenCentral()
    }
}

include(":farebot-base")
include(":farebot-card")
include(":farebot-card-cepas")
include(":farebot-card-classic")
include(":farebot-card-desfire")
include(":farebot-card-felica")
include(":farebot-card-ultralight")
include(":farebot-transit")
include(":farebot-transit-bilhete")
include(":farebot-transit-clipper")
include(":farebot-transit-easycard")
include(":farebot-transit-edy")
include(":farebot-transit-kmt")
include(":farebot-transit-ezlink")
include(":farebot-transit-hsl")
include(":farebot-transit-manly")
include(":farebot-transit-myki")
include(":farebot-transit-octopus")
include(":farebot-transit-opal")
include(":farebot-transit-orca")
include(":farebot-transit-ovc")
include(":farebot-transit-seqgo")
include(":farebot-transit-stub")
include(":farebot-transit-suica")
include(":farebot-app-persist")
include(":farebot-android")
include(":farebot-card-iso7816")
include(":farebot-card-vicinity")
include(":farebot-card-ksx6924")
include(":farebot-card-china")
include(":farebot-transit-serialonly")
include(":farebot-transit-erg")
include(":farebot-transit-nextfare")
include(":farebot-transit-en1545")
include(":farebot-transit-calypso")
include(":farebot-transit-nextfareul")
include(":farebot-transit-ultralight")
include(":farebot-transit-ndef")
include(":farebot-transit-unknown")
include(":farebot-transit-bip")
include(":farebot-transit-bonobus")
include(":farebot-transit-charlie")
include(":farebot-transit-cifial")
include(":farebot-transit-intercard")
include(":farebot-transit-kazan")
include(":farebot-transit-kiev")
include(":farebot-transit-komuterlink")
include(":farebot-transit-magnacarta")
include(":farebot-transit-metromoney")
include(":farebot-transit-metroq")
include(":farebot-transit-mrtj")
include(":farebot-transit-otago")
include(":farebot-transit-oyster")
include(":farebot-transit-pilet")
include(":farebot-transit-podorozhnik")
include(":farebot-transit-selecta")
