name: FareBot
options:
  bundleIdPrefix: com.codebutler.farebot
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - iosApp
    settings:
      base:
        PRODUCT_NAME: FareBot
        INFOPLIST_FILE: iosApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: iosApp/iosApp.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.codebutler.farebot
        SWIFT_VERSION: "5.9"
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: ZJ9GEQ36AH
        CODE_SIGN_STYLE: Automatic
        FRAMEWORK_SEARCH_PATHS:
          - "$(SRCROOT)/../farebot-shared/build/XCFrameworks/release"
          - "$(SRCROOT)/../farebot-shared/build/bin/iosSimulatorArm64/debugFramework"
          - "$(SRCROOT)/../farebot-shared/build/bin/iosArm64/debugFramework"
          - "$(SRCROOT)/../farebot-shared/build/bin/iosX64/debugFramework"
        OTHER_LDFLAGS:
          - "-framework"
          - "FareBotKit"
          - "-lsqlite3"
    attributes:
      SystemCapabilities:
        com.apple.NearFieldCommunicationTagReading:
          enabled: 1
    dependencies:
      - framework: "../farebot-shared/build/bin/iosSimulatorArm64/debugFramework/FareBotKit.framework"
        embed: true
    preBuildScripts:
      - name: "Build KMP Framework"
        script: |
          cd "$SRCROOT/.."
          ./gradlew :farebot-shared:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
