/*
 * SampleTransitDataDumpTest.kt
 *
 * This file is part of FareBot.
 * Learn more at: https://codebutler.github.io/farebot/
 *
 * Copyright (C) 2025 Eric Butler <eric@codebutler.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.codebutler.farebot.test

import com.codebutler.farebot.base.ui.HeaderListItem
import com.codebutler.farebot.base.ui.ListItemInterface
import com.codebutler.farebot.base.util.DefaultStringResource
import com.codebutler.farebot.shared.serialize.CardImporter
import com.codebutler.farebot.shared.serialize.ImportResult
import com.codebutler.farebot.shared.serialize.KotlinxCardSerializer
import com.codebutler.farebot.shared.transit.TransitFactoryRegistry
import com.codebutler.farebot.shared.transit.createTransitFactoryRegistry
import com.codebutler.farebot.transit.Subscription
import com.codebutler.farebot.transit.Trip
import kotlinx.serialization.json.Json
import kotlin.test.Test

class SampleTransitDataDumpTest {
    private val json =
        Json {
            isLenient = true
            ignoreUnknownKeys = true
        }

    private val serializer = KotlinxCardSerializer(json)
    private val importer = CardImporter.create(serializer, json)
    private val registry: TransitFactoryRegistry = createTransitFactoryRegistry(DefaultStringResource())

    data class SampleCard(
        val name: String,
        val resourcePath: String,
        val format: Format,
    ) {
        enum class Format { METRODROID_JSON, MFC_BINARY, FLIPPER_NFC }
    }

    private val samples =
        listOf(
            SampleCard("Opal", "opal/Opal.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("HSLv2", "hsl/HSLv2.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("HSL_UL", "hsl/HSL_UL.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("TroikaUL", "troika/TroikaUL.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("TMoney", "tmoney/TMoney.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("EZLink", "cepas/EZLink.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("Holo", "holo/Holo.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("Mobib", "mobib/Mobib.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("Compass", "compass/Compass.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("SeqGo", "seqgo/SeqGo.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("LaxTap", "laxtap/LaxTap.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("MspGoTo", "mspgoto/MspGoTo.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("Myki", "myki/Myki.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("Octopus", "octopus/Octopus.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("TrimetHop", "trimethop/TrimetHop.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("BilheteUnico", "bilhete/BilheteUnico.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("Ventra", "ventra/Ventra.json", SampleCard.Format.METRODROID_JSON),
            SampleCard("EasyCard", "easycard/deadbeef.mfc", SampleCard.Format.MFC_BINARY),
            SampleCard("Clipper", "flipper/Clipper.nfc", SampleCard.Format.FLIPPER_NFC),
            SampleCard("ICOCA", "flipper/ICOCA.nfc", SampleCard.Format.FLIPPER_NFC),
            SampleCard("ORCA", "flipper/ORCA.nfc", SampleCard.Format.FLIPPER_NFC),
            SampleCard("PASMO", "flipper/PASMO.nfc", SampleCard.Format.FLIPPER_NFC),
            SampleCard("Suica", "flipper/Suica.nfc", SampleCard.Format.FLIPPER_NFC),
        )

    @Test
    fun dumpAllSampleTransitData() {
        val output =
            buildString {
                appendLine("# FareBot Sample Transit Data Dump")
                appendLine("# Generated by SampleTransitDataDumpTest")
                appendLine()
                appendLine("cards:")

                for (sample in samples) {
                    try {
                        appendLine(processSample(sample))
                    } catch (e: Exception) {
                        appendLine("  - name: \"${sample.name}\"")
                        appendLine("    error: \"${e::class.simpleName}: ${yamlEscape(e.message ?: "unknown")}\"")
                    }
                }
            }

        print(output)
    }

    private fun processSample(sample: SampleCard): String {
        val bytes =
            loadTestResource(sample.resourcePath)
                ?: return "  - name: \"${sample.name}\"\n    error: \"Missing resource: ${sample.resourcePath}\""

        val rawCard =
            when (sample.format) {
                SampleCard.Format.METRODROID_JSON -> {
                    val result = importer.importCards(bytes.decodeToString())
                    when (result) {
                        is ImportResult.Success -> result.cards.first()
                        is ImportResult.Error -> {
                            val err = yamlEscape(result.message)
                            return "  - name: \"${sample.name}\"\n" +
                                "    error: \"Import error: $err\""
                        }
                    }
                }
                SampleCard.Format.MFC_BINARY -> {
                    val result = importer.importMfcDump(bytes)
                    when (result) {
                        is ImportResult.Success -> result.cards.first()
                        is ImportResult.Error -> {
                            val err = yamlEscape(result.message)
                            return "  - name: \"${sample.name}\"\n" +
                                "    error: \"Import error: $err\""
                        }
                    }
                }
                SampleCard.Format.FLIPPER_NFC -> {
                    val result = importer.importCards(bytes.decodeToString())
                    when (result) {
                        is ImportResult.Success -> result.cards.first()
                        is ImportResult.Error -> {
                            val err = yamlEscape(result.message)
                            return "  - name: \"${sample.name}\"\n" +
                                "    error: \"Import error: $err\""
                        }
                    }
                }
            }

        val card = rawCard.parse()
        val identity = registry.parseTransitIdentity(card)
        val info = registry.parseTransitInfo(card)
        val cardName = identity?.name ?: sample.name

        return buildString {
            appendLine("  - name: \"$cardName\"")
            appendLine("    sample: \"${sample.name}\"")

            if (info == null) {
                appendLine("    error: \"No transit info - no matching factory\"")
                return@buildString
            }

            appendLine("    serial: ${yamlValue(info.serialNumber)}")

            // Balances
            val balances = info.balances
            if (balances != null && balances.isNotEmpty()) {
                appendLine("    balances:")
                for (bal in balances) {
                    appendLine("      - name: ${yamlValue(bal.name)}")
                    appendLine("        amount: \"${bal.balance.formatCurrencyString(isBalance = true)}\"")
                }
            } else {
                appendLine("    balances: []")
            }

            // Trips
            val trips = info.trips
            if (trips != null && trips.isNotEmpty()) {
                appendLine("    trips:")
                for (trip in trips.sortedWith(Trip.Comparator())) {
                    formatTrip(trip, this)
                }
            } else {
                appendLine("    trips: ${if (trips == null) "null" else "[]"}")
            }

            // Subscriptions
            val subs = info.subscriptions
            if (subs != null && subs.isNotEmpty()) {
                appendLine("    subscriptions:")
                for (sub in subs) {
                    formatSubscription(sub, this)
                }
            } else {
                appendLine("    subscriptions: ${if (subs == null) "null" else "[]"}")
            }

            // Info items
            val infoItems = info.info
            if (infoItems != null && infoItems.isNotEmpty()) {
                appendLine("    info:")
                for (item in infoItems) {
                    formatInfoItem(item, this)
                }
            } else {
                appendLine("    info: ${if (infoItems == null) "null" else "[]"}")
            }

            // Empty state
            if (info.emptyStateMessage != null) {
                appendLine("    emptyState: \"${yamlEscape(info.emptyStateMessage!!)}\"")
            }

            // Warning
            if (info.warning != null) {
                appendLine("    warning: \"${yamlEscape(info.warning!!)}\"")
            }
        }.trimEnd()
    }

    private fun formatTrip(
        trip: Trip,
        sb: StringBuilder,
    ) {
        val ts = trip.startTimestamp ?: trip.endTimestamp
        sb.appendLine("      - timestamp: ${if (ts != null) "\"$ts\"" else "null"}")
        sb.appendLine("        mode: ${trip.mode}")
        sb.appendLine("        agency: ${yamlValue(trip.shortAgencyName)}")
        sb.appendLine("        route: ${yamlValue(trip.routeName)}")
        sb.appendLine("        startStation: ${yamlValue(trip.startStation?.stationName)}")
        sb.appendLine("        endStation: ${yamlValue(trip.endStation?.stationName)}")
        val fareStr = trip.fare?.formatCurrencyString() ?: trip.fareString
        sb.appendLine("        fare: ${yamlValue(fareStr)}")
        if (trip.isTransfer) sb.appendLine("        transfer: true")
        if (trip.isRejected) sb.appendLine("        rejected: true")
    }

    private fun formatSubscription(
        sub: Subscription,
        sb: StringBuilder,
    ) {
        sb.appendLine("      - name: ${yamlValue(sub.subscriptionName)}")
        sb.appendLine("        agency: ${yamlValue(sub.agencyName)}")
        sb.appendLine("        validity: ${yamlValue(sub.formatValidity())}")
        if (sub.subscriptionState != Subscription.SubscriptionState.UNKNOWN) {
            sb.appendLine("        state: ${sub.subscriptionState}")
        }
        val remaining = sub.formatRemainingTrips()
        if (remaining != null) {
            sb.appendLine("        remaining: \"${yamlEscape(remaining)}\"")
        }
    }

    private fun formatInfoItem(
        item: ListItemInterface,
        sb: StringBuilder,
    ) {
        if (item is HeaderListItem) {
            sb.appendLine("      - header: ${yamlValue(item.text1)}")
        } else {
            sb.appendLine("      - label: ${yamlValue(item.text1)}")
            sb.appendLine("        value: ${yamlValue(item.text2)}")
        }
    }

    private fun yamlValue(value: String?): String =
        when {
            value == null -> "null"
            value.isEmpty() -> "\"\""
            else -> "\"${yamlEscape(value)}\""
        }

    private fun yamlEscape(value: String): String =
        value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
}
